### ISSUE TITLE
Option to include all saved albums rather than saved songs

### ISSUE THREAD

**Issue by danielandrews** [Shpigford/plylst#65]
Spotify has recently changed the behavior of how liking an album works. A user can now save an album to their library without adding every song. This can create an issue where there's no criteria to filter based on all albums in your library.

If possible, this could be added as another filter criteria.

**Comment by Shpigford** [comment]
@danielandrews Just rolled out a fix to properly import saved albums, so those songs should now be included in your playlists!

**Comment by Shpigford** [comment]
@danielandrews And just as an FYI, it will take up to 24 hours to get all of those imported historically. I've started the process to update everyone's libraries but it takes a while to do it without overloading Spotify's API.

**Comment by vokinpirks** [comment]
Not sure if it's an appropriate place to discuss this, but what if I don't want to include tracks from saved albums? Personally, I save albums to my library to check them out later. Once I've listened to an album enough I remove it even if I actually liked it. Saved albums is rather a backlog/to-listen thing for me. I wonder who ever saves an album just to mark all the tracks from it as liked ones. It makes no sense because Spotify doesn't know that you indeed liked those.
I think this should be a dedicated option: "Songs from saved albums" or whatever.
